In [ ]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.model_selection import cross_validate

train_data = pd.read_csv("../data/processed/data_with_scalling/cleaned_train_Scaling.csv")
test_data  = pd.read_csv("../data/processed/data_with_scalling/cleaned_test_Scaling.csv")

X_train = train_data.drop("Heart Disease", axis=1)
y_train = train_data["Heart Disease"]
X_test  = test_data.drop("Heart Disease", axis=1)
y_test  = test_data["Heart Disease"]


models = {
    "C=0.001, L2": LogisticRegression(C=0.001, penalty='l2', solver='lbfgs',     max_iter=1000),
    "C=0.1,   L2": LogisticRegression(C=0.1,   penalty='l2', solver='lbfgs',     max_iter=1000),
    "C=1,     L2": LogisticRegression(C=1,     penalty='l2', solver='lbfgs',     max_iter=1000),
    "C=10,    L2": LogisticRegression(C=10,    penalty='l2', solver='lbfgs',     max_iter=1000),
    "C=0.001, L1": LogisticRegression(C=0.001, penalty='l1', solver='liblinear', max_iter=1000),
    "C=0.1,   L1": LogisticRegression(C=0.1,   penalty='l1', solver='liblinear', max_iter=1000),
    "C=1,     L1": LogisticRegression(C=1,     penalty='l1', solver='liblinear', max_iter=1000),
    "C=10,    L1": LogisticRegression(C=10,    penalty='l1', solver='liblinear', max_iter=1000),
}

for name, model in models.items():
    print(f"\n===== {name} =====")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print("Accuracy :", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, zero_division=0))
    print("Recall   :", recall_score(y_test, y_pred, zero_division=0))
    print("F1-score :", f1_score(y_test, y_pred, zero_division=0))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

    

    cv_results = cross_validate(
        model, X_train, y_train,
        cv=5,
        scoring=['accuracy', 'precision', 'recall', 'f1']
    )
   
    print("Avg Accuracy  :", cv_results['test_accuracy'].mean())
    print("Avg Precision :", cv_results['test_precision'].mean())
    print("Avg Recall    :", cv_results['test_recall'].mean())
    print("Avg F1        :", cv_results['test_f1'].mean())




===== C=0.001, L2 =====
Accuracy : 0.8
Precision: 0.9333333333333333
Recall   : 0.5833333333333334
F1-score : 0.717948717948718
Confusion Matrix:
 [[30  1]
 [10 14]]


c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was depreca

Avg Accuracy  : 0.7302325581395348
Avg Precision : 0.9214141414141415
Avg Recall    : 0.4373684210526315
Avg F1        : 0.5915897146152986

===== C=0.1,   L2 =====
Accuracy : 0.8727272727272727
Precision: 0.9047619047619048
Recall   : 0.7916666666666666
F1-score : 0.8444444444444444
Confusion Matrix:
 [[29  2]
 [ 5 19]]


c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was depreca

Avg Accuracy  : 0.8279069767441861
Avg Precision : 0.853353705118411
Avg Recall    : 0.76
Avg F1        : 0.7983016983016983

===== C=1,     L2 =====
Accuracy : 0.8727272727272727
Precision: 0.9047619047619048
Recall   : 0.7916666666666666
F1-score : 0.8444444444444444
Confusion Matrix:
 [[29  2]
 [ 5 19]]


c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was depreca

Avg Accuracy  : 0.8186046511627907
Avg Precision : 0.8249689440993789
Avg Recall    : 0.7699999999999999
Avg F1        : 0.7904621248533698

===== C=10,    L2 =====
Accuracy : 0.8727272727272727
Precision: 0.9047619047619048
Recall   : 0.7916666666666666
F1-score : 0.8444444444444444
Confusion Matrix:
 [[29  2]
 [ 5 19]]


c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was depreca

Avg Accuracy  : 0.8046511627906977
Avg Precision : 0.8023969013442699
Avg Recall    : 0.76
Avg F1        : 0.7759722117345011

===== C=0.001, L1 =====
Accuracy : 0.5636363636363636
Precision: 0.0
Recall   : 0.0
F1-score : 0.0
Confusion Matrix:
 [[31  0]
 [24  0]]


c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  wa

Avg Accuracy  : 0.5534883720930233
Avg Precision : 0.0
Avg Recall    : 0.0
Avg F1        : 0.0

===== C=0.1,   L1 =====
Accuracy : 0.8545454545454545
Precision: 0.9
Recall   : 0.75
F1-score : 0.8181818181818182
Confusion Matrix:
 [[29  2]
 [ 6 18]]


c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2

Avg Accuracy  : 0.7627906976744185
Avg Precision : 0.7356091617933723
Avg Recall    : 0.758421052631579
Avg F1        : 0.7383533315928001

===== C=1,     L1 =====
Accuracy : 0.8727272727272727
Precision: 0.9047619047619048
Recall   : 0.7916666666666666
F1-score : 0.8444444444444444
Confusion Matrix:
 [[29  2]
 [ 5 19]]


c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2

Avg Accuracy  : 0.8046511627906977
Avg Precision : 0.8044677871148458
Avg Recall    : 0.7494736842105263
Avg F1        : 0.7728295871194006

===== C=10,    L1 =====
Accuracy : 0.8727272727272727
Precision: 0.9047619047619048
Recall   : 0.7916666666666666
F1-score : 0.8444444444444444
Confusion Matrix:
 [[29  2]
 [ 5 19]]


c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2

Avg Accuracy  : 0.8093023255813954
Avg Precision : 0.8093233082706768
Avg Recall    : 0.76
Avg F1        : 0.7798746507588914
